# Generated by Django 2.0.3 on 2018-03-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.IntegerField()),
                ('eventTime', models.DateTimeField()),
                ('content', models.CharField(default='', max_length=2000)),
                ('ctime', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mytime_task',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('ctime', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mytime_user',
            },
        ),
        migrations.CreateModel(
            name='UserTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('timeline', models.IntegerField()),
                ('spendtime', models.IntegerField()),
                ('taskid', models.IntegerField()),
                ('ctime', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mytime_usertimeline',
            },
        ),
    ]
